# Generated by Django 5.2.8 on 2025-11-27 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('doctrine_type', models.CharField(blank=True, help_text="e.g. 'Nano Gang' or 'Heavy Armor'", max_length=50)),
                ('fc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_fleets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_text', models.TextField()),
                ('ship_name', models.CharField(default='Unknown Ship', max_length=100)),
                ('role', models.CharField(choices=[('xup', 'X Up'), ('dps', 'DPS'), ('logi', 'Logistics'), ('sniper', 'Sniper')], default='xup', max_length=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fleets.fleet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
